"""Compare calibration-only residual distributions on the frozen untouched test.

The point model is a state-specific linear extrapolation of the last two
calibration observations. Residuals are generated by rolling-origin forecasts
whose training and target years are both inside 2010-2017. Test outcomes are
read only after all residual pools and state/region scales are constructed.
"""
from __future__ import annotations

import argparse
import csv
import json
import math
import random
from collections import defaultdict
from pathlib import Path
from statistics import mean, pstdev


REGIONS = {
    "Northeast": {"09", "23", "25", "33", "34", "36", "42", "44", "50"},
    "Midwest": {"17", "18", "19", "20", "26", "27", "29", "31", "38", "39", "46", "55"},
    "South": {"01", "05", "10", "11", "12", "13", "21", "22", "24", "28", "37", "40", "45", "47", "48", "51", "54"},
    "West": {"02", "04", "06", "08", "15", "16", "30", "32", "35", "41", "49", "53", "56"},
}
TEST_YEARS = (2018, 2019, 2021)
CALIBRATION_END = 2017
MIN_SCALE = 0.25


def region_for_state(state: str) -> str:
    code = str(state).zfill(2)
    return next((name for name, codes in REGIONS.items() if code in codes), "Unknown")


def point_forecast(rows: list[dict], year: int) -> float:
    ordered = sorted(rows, key=lambda row: row["year"])
    if len(ordered) < 2:
        return float(ordered[-1]["value"])
    previous, last = ordered[-2:]
    step = last["year"] - previous["year"]
    slope = (last["value"] - previous["value"]) / max(1, step)
    return max(0.0, last["value"] + slope * (year - last["year"]))


def rolling_calibration_residuals(rows: list[dict], end_year: int = CALIBRATION_END) -> list[dict]:
    by_state: dict[str, list[dict]] = defaultdict(list)
    for row in rows:
        if row["year"] <= end_year:
            by_state[row["state"]].append(row)
    residuals = []
    for state, history in by_state.items():
        history.sort(key=lambda row: row["year"])
        by_year = {row["year"]: row for row in history}
        for origin_index in range(1, len(history)):
            prior = history[:origin_index + 1]
            origin = prior[-1]["year"]
            for horizon in (1, 2, 4):
                target = by_year.get(origin + horizon)
                if target is None or target["year"] > end_year:
                    continue
                residuals.append({
                    "state": state,
                    "region": region_for_state(state),
                    "origin_year": origin,
                    "target_year": target["year"],
                    "horizon": horizon,
                    "residual": target["value"] - point_forecast(prior, target["year"]),
                })
    return residuals


def centered(values: list[float]) -> list[float]:
    if not values:
        return []
    location = mean(values)
    return [value - location for value in values]


def sd(values: list[float]) -> float:
    return max(pstdev(values) if len(values) > 1 else 0.0, MIN_SCALE)


def empirical_quantile(values: list[float], probability: float, *, presorted: bool = False) -> float:
    ordered = values if presorted else sorted(values)
    if len(ordered) == 1:
        return ordered[0]
    position = probability * (len(ordered) - 1)
    lower = int(position)
    upper = min(lower + 1, len(ordered) - 1)
    weight = position - lower
    return ordered[lower] * (1 - weight) + ordered[upper] * weight


def pool_for(residuals: list[dict], horizon: int, *, state: str | None = None,
             region: str | None = None) -> list[float]:
    return [float(row["residual"]) for row in residuals
            if row["horizon"] == horizon
            and (state is None or row["state"] == state)
            and (region is None or row["region"] == region)]


def scaled_draw(rng: random.Random, residuals: list[dict], horizon: int,
                state: str, region: str, scale_mode: str,
                distribution: str, cache: dict) -> tuple[float, float, int]:
    key = (horizon, state, region, scale_mode)
    if key not in cache:
        global_values = centered(pool_for(residuals, horizon))
        region_values = centered(pool_for(residuals, horizon, region=region)) or global_values
        state_values = centered(pool_for(residuals, horizon, state=state))
        global_sd = sd(global_values)
        region_sd = sd(region_values)
        state_n = len(state_values)
        shrink = state_n / (state_n + 10.0)
        state_sd = sd(state_values) if state_values else region_sd
        shrunken_sd = math.sqrt(shrink * state_sd**2 + (1 - shrink) * region_sd**2)
        cache[key] = {
            "global": (global_values, global_sd, sorted(global_values)),
            "region": (region_values, region_sd, sorted(region_values)),
            "state": (state_values or region_values,
                      sd(state_values) if state_values else region_sd,
                      sorted(state_values or region_values)),
            "target_sd": global_sd if scale_mode == "pooled" else
                        region_sd if scale_mode == "region" else shrunken_sd,
            "shrink": shrink,
        }
    prepared = cache[key]
    if scale_mode == "pooled":
        source, source_sd, ordered = prepared["global"]
    elif scale_mode == "region":
        source, source_sd, ordered = prepared["region"]
    elif rng.random() < prepared["shrink"]:
        source, source_sd, ordered = prepared["state"]
    else:
        source, source_sd, ordered = prepared["region"]
    target_sd = prepared["target_sd"]
    if distribution == "normal":
        return rng.gauss(0.0, target_sd), target_sd, len(source)
    if distribution == "empirical_quantile":
        draw = empirical_quantile(ordered, rng.random(), presorted=True) * target_sd / source_sd
    else:
        draw = rng.choice(source) * target_sd / source_sd
    return draw, target_sd, len(source)


def crps(observed: float, samples: list[float]) -> float:
    ordered = sorted(samples)
    count = len(ordered)
    first = sum(abs(value - observed) for value in ordered) / count
    pairwise = sum((2 * index - count + 1) * value
                   for index, value in enumerate(ordered)) / (count**2)
    return first - pairwise


def clustered_bootstrap(scores: list[dict], *, seed: int, draws: int = 1000) -> dict:
    by_state: dict[str, list[dict]] = defaultdict(list)
    for row in scores:
        by_state[row["state"]].append(row)
    states = sorted(by_state)
    rng = random.Random(seed)
    estimates = {name: [] for name in ("crps", "coverage", "interval_width")}
    for _ in range(draws):
        selected = [states[rng.randrange(len(states))] for _ in states]
        sample = [row for state in selected for row in by_state[state]]
        estimates["crps"].append(mean(row["crps"] for row in sample))
        estimates["coverage"].append(mean(float(row["covered"]) for row in sample))
        estimates["interval_width"].append(mean(row["interval_width"] for row in sample))
    intervals = {}
    for name, values in estimates.items():
        values.sort()
        intervals[name] = {
            "lower_95": values[int(0.025 * (draws - 1))],
            "upper_95": values[int(0.975 * (draws - 1))],
        }
    return {"unit": "state_cluster", "draws": draws, "intervals": intervals}


def summarize_candidate(observed_rows: list[dict], calibration_rows: list[dict], residuals: list[dict], scale_mode: str,
                        distribution: str, draws: int, seed: int) -> dict:
    rng = random.Random(seed)
    scores = []
    stratum: dict[str, list[dict]] = defaultdict(list)
    distribution_cache = {}
    for row in observed_rows:
        history = [item for item in calibration_rows if item["state"] == row["state"]]
        forecast = point_forecast(history, row["year"])
        horizon = row["year"] - max(item["year"] for item in calibration_rows)
        residual_samples = [scaled_draw(rng, residuals, horizon, row["state"], row["region"],
                                        scale_mode, distribution, distribution_cache)[0]
                           for _ in range(draws)]
        predictive = [max(0.0, forecast + error) for error in residual_samples]
        predictive.sort()
        lo = predictive[int(0.10 * (len(predictive) - 1))]
        hi = predictive[int(0.90 * (len(predictive) - 1))]
        score = {
            "state": row["state"], "region": row["region"], "year": row["year"],
            "observed": row["value"], "point": forecast,
            "mape": abs(forecast - row["value"]) / max(abs(row["value"]), 1e-9),
            "rmse_component": (forecast - row["value"]) ** 2,
            "crps": crps(row["value"], predictive),
            "covered": lo <= row["value"] <= hi,
            "interval_width": hi - lo,
            "interval_lower": lo,
            "interval_upper": hi,
        }
        scores.append(score)
        stratum[row["region"]].append(score)
    return {
        "scale": scale_mode,
        "distribution": distribution,
        "nominal_coverage": 0.8,
        "n": len(scores),
        "mape": mean(row["mape"] for row in scores),
        "rmse": math.sqrt(mean(row["rmse_component"] for row in scores)),
        "crps": mean(row["crps"] for row in scores),
        "coverage": mean(float(row["covered"]) for row in scores),
        "coverage_gap": mean(float(row["covered"]) for row in scores) - 0.8,
        "mean_interval_width": mean(row["interval_width"] for row in scores),
        "cluster_bootstrap_95": clustered_bootstrap(scores, seed=seed + 9001),
        "by_region": {
            group: {
                "n": len(items),
                "coverage": mean(float(row["covered"]) for row in items),
                "crps": mean(row["crps"] for row in items),
                "mean_interval_width": mean(row["interval_width"] for row in items),
            }
            for group, items in sorted(stratum.items())
        },
        "scores": scores,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("panel", type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--draws", type=int, default=1000)
    parser.add_argument("--seed", type=int, default=20260929)
    args = parser.parse_args()
    with args.panel.open(encoding="utf-8-sig", newline="") as handle:
        raw = list(csv.DictReader(handle))
    rows = [{"state": str(row["state"]).zfill(2), "year": int(row["year"]),
             "value": float(row["asfr_15_44"]), "region": region_for_state(row["state"])}
            for row in raw]
    calibration = [row for row in rows if row["year"] <= CALIBRATION_END]
    observed_test = [row for row in rows if row["year"] in TEST_YEARS]
    if len(observed_test) != 50 * len(TEST_YEARS):
        raise SystemExit(f"unexpected_test_key_count={len(observed_test)}")
    scale_modes = ("pooled", "region", "state_shrunk")
    distributions = ("normal", "empirical_quantile", "bootstrap_residual")
    validation_scores: dict[tuple[str, str], list[dict]] = defaultdict(list)
    validation_folds = []
    for validation_year in (2016, 2017):
        cutoff = validation_year - 1
        fit_rows = [row for row in rows if row["year"] <= cutoff]
        validation_rows = [row for row in rows if row["year"] == validation_year]
        fit_residuals = rolling_calibration_residuals(fit_rows, end_year=cutoff)
        validation_folds.append({"validation_year": validation_year, "fit_through": cutoff,
                                 "fit_residuals": len(fit_residuals),
                                 "validation_state_rows": len(validation_rows)})
        for scale_index, scale_mode in enumerate(scale_modes):
            for dist_index, distribution in enumerate(distributions):
                report = summarize_candidate(
                    validation_rows, fit_rows, fit_residuals, scale_mode, distribution,
                    args.draws, args.seed + validation_year * 1009 + scale_index * 101 + dist_index,
                )
                validation_scores[(scale_mode, distribution)].extend(report["scores"])

    def summarize_scores(scores: list[dict], scale_mode: str, distribution: str, seed: int) -> dict:
        return {
            "scale": scale_mode, "distribution": distribution, "nominal_coverage": 0.8,
            "n": len(scores),
            "mape": mean(row["mape"] for row in scores),
            "rmse": math.sqrt(mean(row["rmse_component"] for row in scores)),
            "crps": mean(row["crps"] for row in scores),
            "coverage": mean(float(row["covered"]) for row in scores),
            "coverage_gap": mean(float(row["covered"]) for row in scores) - 0.8,
            "mean_interval_width": mean(row["interval_width"] for row in scores),
            "cluster_bootstrap_95": clustered_bootstrap(scores, seed=seed),
        }

    validation_results = [
        summarize_scores(scores, scale_mode, distribution, args.seed + index)
        for index, ((scale_mode, distribution), scores) in enumerate(validation_scores.items())
    ]
    coverage_tolerance = 0.10
    eligible = [row for row in validation_results if abs(row["coverage_gap"]) <= coverage_tolerance]
    if eligible:
        selected = min(eligible, key=lambda row: (row["crps"], row["mean_interval_width"]))
        selection_rule = "minimum calibration-validation CRPS among candidates within 10 percentage points of nominal 80% coverage"
    else:
        selected = min(validation_results, key=lambda row: (abs(row["coverage_gap"]), row["crps"]))
        selection_rule = "no candidate met coverage tolerance; selected smallest calibration-validation coverage gap, then CRPS"

    residuals = rolling_calibration_residuals(calibration, end_year=CALIBRATION_END)
    if any(row["target_year"] > CALIBRATION_END for row in residuals):
        raise SystemExit("calibration_residual_leaked_test_year")
    final_test = summarize_candidate(
        observed_test, calibration, residuals, selected["scale"], selected["distribution"],
        args.draws, args.seed + 88001,
    )
    final_test.pop("scores", None)
    validation_results.sort(key=lambda row: (row["crps"], abs(row["coverage_gap"]), row["mean_interval_width"]))
    payload = {
        "version": "2026-09-29",
        "kind": "calibration_only_residual_uncertainty_comparison",
        "point_model": "state_specific_linear_trend_from_last_two_calibration_observations",
        "calibration_years": list(range(2010, 2018)),
        "untouched_test_years": list(TEST_YEARS),
        "residual_construction": "expanding-window forecast errors at horizons 1, 2 and 4; each training and target year is within 2010-2017",
        "residual_count": len(residuals),
        "residual_counts_by_horizon": {
            str(h): len([row for row in residuals if row["horizon"] == h])
            for h in sorted({row["horizon"] for row in residuals})
        },
        "scale_methods": {
            "pooled": "all calibration residuals at matching forecast horizon",
            "region": "Census-region calibration residuals at matching horizon",
            "state_shrunk": "state residuals partially pooled toward region with weight n/(n+10)",
        },
        "distributions": {
            "normal": "zero-mean Gaussian using calibration-only scale",
            "empirical_quantile": "linearly interpolated empirical residual quantiles, rescaled to target variance",
            "bootstrap_residual": "discrete resampling of centered calibration residuals, rescaled to target variance",
        },
        "draws_per_state_year": args.draws,
        "calibration_validation": {
            "years": [2016, 2017], "folds": validation_folds,
            "selection_rule": selection_rule, "coverage_tolerance": coverage_tolerance,
            "selected_scale": selected["scale"],
            "selected_distribution": selected["distribution"],
            "candidate_results": validation_results,
        },
        "final_test_result_selected_once": final_test,
        "other_test_candidates_evaluated": False,
        "interpretation": "方法仅由校准期内2016-2017滚动验证选择；随后用完整2010-2017重估，2018、2019、2021只评估一次。",
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"output": str(args.output), "residuals": len(residuals),
                      "test_rows": len(observed_test),
                      "selected": {"scale": selected["scale"], "distribution": selected["distribution"]},
                      "final_test": {key: final_test[key] for key in
                                     ("crps", "coverage", "mean_interval_width", "mape", "rmse")}},
                     ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
